config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  post "/create-notice", to: "notices#create"
  get "/notifications", to: "notices#notifications"
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notice.rb
class Notice < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"

  after_commit -> { NotificationRelayJob.perform_later(self) }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :notices
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id)
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  def create
    @notice = Notice.new(notice_params)
    respond_to do |format|
      if @notice.save
        format.html { redirect_to root_path }
      end
    end
  end

  def notifications
    @notices = Notice.where(recipient: current_user)
    respond_to do |format|
      format.js
    end
  end

  private

  def notice_params
    params.require(:notice).permit(:body, :sender_id, :recipient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/views/home/index.html.erb
<table>
  <thead>
  <tr>
    <th>Email</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><!-- Modal Trigger -->
        <a class="waves-effect waves-light btn modal-trigger" href="#modal1" onclick="modalRecipient(<%= user.id %>)" >Notice</a>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<!-- Modal Structure -->
<div id="modal1" class="modal">
  <div class="modal-content">
    <h4>New Notice</h4>
    <%= form_with scope: Notice.new, url: create_notice_path, local: true do |f| %>
      Message: <%= f.text_field :body %>
      <%= f.text_field :recipient_id, id:'recipient', hidden:true%>
      <%= f.text_field :sender_id, hidden:true, value:current_user.id %>
      <button class="btn waves-effect waves-light" type="submit" name="action">Submit
        <i class="material-icons right">send</i>
      </button>
    <% end %>
  </div>
</div>
<script>
    function modalRecipient(recipientId) {
        $('#recipient').val(recipientId);
    };
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notifications</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    "application", media: "all", "data-    turbolinks-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
</head>
<body>
<%= render partial: "partials/navbar"%>
<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
</body>
</html>

app/views/notices/_new_notification.html.erb
<li><a href='#!'><b><%= notification.sender.email %></b> <%= notification.body %></a></li>

app/views/notices/notifications.js.erb
var notification = '';
<% if @notices.length < 1 %>
notification = '<li><a href="#!">No notification</a></li>';
<% else %>
<% @notices.reverse_each do |notice| %>
notification += "<li><a href=''#!'><b><%= notice.sender.email %></b> <%= notice.body %></a></li>";
<% end %>
<% end %>
$('[data-behavior~=notices]').prepend(notification);

app/views/partials/_navbar.html.erb
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><a href="#!">Notifications</a></li>
  <li class="divider"></li>
  <div data-behavior="notices">
  </div>
</ul>
<nav>
  <div class="nav-wrapper">
    <div class="container">
      <div class="brand-logo">
        <%= link_to("Notifications", notifications_path) %>
      </div>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><i class="material-icons">notifications</i></a></li>
        <li>
          <%= link_to("Logout", destroy_user_session_path, method: :delete) %>
        </li>
      </ul>
    </div>
  </div>
</nav>